"""Write validated representative planar regions as Gmsh built-in geometry."""

from __future__ import annotations

from collections import defaultdict
from dataclasses import dataclass, field
from itertools import product
from pathlib import Path
from typing import Iterable

import numpy as np

from ems_mesh_checker.geometry.circular_geometry import (
    CircularGeometryNormalizer,
    LabeledPrimitive,
)
from ems_mesh_checker.geometry.curve_simplification import (
    CircularArcPrimitive,
    CurvePrimitive,
    CurveSimplificationConfig,
    LinePrimitive,
    simplify_planar_loop,
)
from ems_mesh_checker.geometry.planar_regions import PlanarLoop, PlanarRegionResult
from ems_mesh_checker.geometry.ruled_surfaces import (
    RuledSurfaceConfig,
    RuledSurfacePatch,
    RuledSurfaceResult,
    reconstruct_ruled_surfaces,
)
from ems_mesh_checker.export.volume_topology import (
    SurfaceTopologyRecord,
    VolumeTopologyConfig,
    build_volume_topology,
)


class RepresentativeGeometryExportError(RuntimeError):
    """Raised when no validated representative surface can be exported."""


@dataclass(frozen=True)
class RepresentativeCurveGroup:
    """One Property-labelled group of representative line/arc primitives."""

    label: str
    primitives: tuple[CurvePrimitive, ...]


def write_planar_regions_geo(
    results: PlanarRegionResult | Iterable[PlanarRegionResult],
    path: str | Path,
    *,
    mesh_size: float = 1.0,
    curve_config: CurveSimplificationConfig | None = None,
    ruled_surface_config: RuledSurfaceConfig | None = None,
    volume_topology_config: VolumeTopologyConfig | None = None,
    circle_elements_per_turn: int | None = None,
) -> Path:
    """Write simplified surfaces and validated Property volumes.

    Unsupported regions are written as comments, never flattened or emitted as
    potentially invalid surfaces. Circular samples are conservatively replaced
    by Gmsh ``Circle`` arcs; all other edges remain ``Line`` entities. Coincident
    points, curves and interface surfaces are shared. Only connected Property
    components whose curves all have degree two become ``Volume`` entities.
    ``circle_elements_per_turn`` optionally writes angle-scaled ``Transfinite
    Curve`` node counts for every emitted arc. Entity IDs and ordering are
    deterministic.
    """

    if mesh_size <= 0.0:
        raise ValueError("mesh_size must be positive")
    if circle_elements_per_turn is not None and circle_elements_per_turn < 3:
        raise ValueError("circle_elements_per_turn must be at least 3")
    region_results = (results,) if isinstance(results, PlanarRegionResult) else tuple(results)
    if not any(result.regions for result in region_results):
        raise RepresentativeGeometryExportError("no validated planar regions are available")

    lines: list[str] = [
        '// Representative planar geometry generated by ems_mesh_checker',
        'SetFactory("Built-in");',
        '// Use sufficiently fine display tessellation for analytic curves in the Gmsh GUI.',
        'Geometry.NumSubEdges = 100;',
        f"representative_mesh_size = {_number(mesh_size)};",
        "",
    ]
    volume_settings = volume_topology_config or VolumeTopologyConfig()
    point_tolerance = max(
        volume_settings.point_absolute_tolerance,
        _model_extent(region_results) * volume_settings.point_relative_tolerance,
    )
    arc_templates = _unique_arcs(
        tuple(
            arc
            for result in region_results
            for arc in _detected_arcs(result, curve_config)
        ),
        point_tolerance,
    )
    arc_normalizer = CircularGeometryNormalizer(
        arc_templates,
        point_tolerance=point_tolerance,
        curve_config=curve_config,
    )
    ruled_results = tuple(
        reconstruct_ruled_surfaces(
            result,
            curve_config=curve_config,
            config=ruled_surface_config,
            arc_templates=arc_templates,
        )
        for result in region_results
    )
    global_allowed_cap_arcs = tuple(
        arc for ruled in ruled_results for arc in _ruled_cap_arcs(ruled)
    )
    entities = _GmshEntityRegistry(
        lines,
        point_tolerance=point_tolerance,
        arc_normalizer=arc_normalizer,
    )
    _pre_register_representative_points(
        entities,
        region_results,
        ruled_results,
        allowed_cap_arcs=global_allowed_cap_arcs,
        curve_config=curve_config,
        volume_topology_config=volume_settings,
    )
    lines.append("")
    physical_surfaces: dict[str, set[int]] = defaultdict(set)
    physical_curves: dict[str, set[int]] = defaultdict(set)
    topology_records: list[SurfaceTopologyRecord] = []

    for result_index, (result, ruled) in enumerate(zip(region_results, ruled_results)):
        label = _physical_label(result, result_index)
        preserve_unmatched_arcs = (
            volume_settings.enabled
            and result.feature_edges.source_kind == "property"
            and _result_is_three_dimensional(result)
        )
        replaced_regions = set(ruled.replaced_region_indices)
        for region in result.regions:
            if region.region_index in replaced_regions:
                continue
            loops = (region.outer_loop, *region.hole_loops)
            loop_curve_references: list[tuple[int, ...]] = []
            lines.append(
                f"// {label} region={region.region_index} source_faces={len(region.source_face_indices)} "
                f"max_error={region.max_planarity_error:.6g}"
            )
            for loop in loops:
                curve_references = _write_loop(
                    lines,
                    loop,
                    normal=region.normal,
                    curve_config=curve_config,
                    entities=entities,
                    allowed_arcs=global_allowed_cap_arcs,
                    preserve_unmatched_arcs_as_lines=preserve_unmatched_arcs,
                )
                loop_curve_references.append(curve_references)
            surface_id, orientation = entities.add_surface(
                tuple(loop_curve_references),
                kind="plane",
            )
            lines.append("")
            physical_surfaces[label].add(surface_id)
            region_curve_ids = tuple(
                reference for loop_refs in loop_curve_references for reference in loop_refs
            )
            physical_curves[label].update(abs(reference) for reference in region_curve_ids)
            _append_topology_record(
                topology_records,
                result,
                surface_id=surface_id,
                orientation=orientation,
                curve_references=region_curve_ids,
            )

        for patch in ruled.patches:
            lines.append(
                f"// {label} ruled_patch={patch.patch_index} "
                f"source_regions={list(patch.source_region_indices)} "
                f"radius={patch.radius:.9g} max_match_error={patch.max_match_error:.6g}"
            )
            created_surfaces = _write_ruled_patch_surfaces(lines, patch, entities=entities)
            lines.append("")
            for surface_id, orientation, created_curves in created_surfaces:
                physical_surfaces[label].add(surface_id)
                physical_curves[label].update(abs(reference) for reference in created_curves)
                _append_topology_record(
                    topology_records,
                    result,
                    surface_id=surface_id,
                    orientation=orientation,
                    curve_references=created_curves,
                )

        for unsupported in result.unsupported_regions:
            reason = unsupported.reason.replace("\n", " ")
            lines.append(
                f"// UNSUPPORTED {label}: source_faces={list(unsupported.source_face_indices)} reason={reason}"
            )

    topology = build_volume_topology(topology_records, config=volume_settings)
    physical_volumes: dict[str, list[int]] = defaultdict(list)
    surface_loop_id = 1
    volume_id = 1
    for shell in topology.shells:
        shell_label = shell.property_label or f"PROPERTY_P{shell.property_id}"
        surface_refs = ", ".join(str(identifier) for identifier in shell.surface_references)
        lines.append(
            f"// {shell_label} closed_shell={shell.shell_index} "
            f"surfaces={len(shell.surface_references)} curves={shell.curve_count}"
        )
        lines.append(f"Surface Loop({surface_loop_id}) = {{{surface_refs}}};")
        lines.append(f"Volume({volume_id}) = {{{surface_loop_id}}};")
        physical_volumes[shell_label].append(volume_id)
        surface_loop_id += 1
        volume_id += 1
    for component in topology.open_components:
        component_label = component.property_label or f"PROPERTY_P{component.property_id}"
        lines.append(
            f"// OPEN_SHELL {component_label} component={component.component_index} "
            f"surfaces={list(component.surface_ids)} "
            f"boundary_curves={list(component.boundary_curve_ids)} "
            f"non_manifold_curves={list(component.non_manifold_curve_ids)} "
            f"reason={component.reason}"
        )
    if topology.shells or topology.open_components:
        lines.append("")

    if circle_elements_per_turn is not None and entities.circle_angles_degrees:
        lines.append(
            f"// Circular discretization target: {circle_elements_per_turn} elements per turn"
        )
        for curve_id, angle_degrees in sorted(entities.circle_angles_degrees.items()):
            element_count = max(
                1,
                int(round(circle_elements_per_turn * angle_degrees / 360.0)),
            )
            lines.append(f"Transfinite Curve {{{curve_id}}} = {element_count + 1};")
        lines.append("")

    for label in sorted(physical_curves):
        identifiers = ", ".join(str(identifier) for identifier in sorted(physical_curves[label]))
        lines.append(f'Physical Curve("{label}") = {{{identifiers}}};')
    for label in sorted(physical_surfaces):
        identifiers = ", ".join(str(identifier) for identifier in sorted(physical_surfaces[label]))
        lines.append(f'Physical Surface("{label}") = {{{identifiers}}};')
    for label in sorted(physical_volumes):
        identifiers = ", ".join(str(identifier) for identifier in physical_volumes[label])
        lines.append(f'Physical Volume("{label}") = {{{identifiers}}};')

    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    return output


def collect_representative_curve_groups(
    results: PlanarRegionResult | Iterable[PlanarRegionResult],
    *,
    curve_config: CurveSimplificationConfig | None = None,
    ruled_surface_config: RuledSurfaceConfig | None = None,
    volume_topology_config: VolumeTopologyConfig | None = None,
) -> tuple[RepresentativeCurveGroup, ...]:
    """Collect the same accepted line/arc geometry used by the GEO writer.

    The returned groups contain no surfaces or volumes and are intended for
    curve-only interchange formats such as DXF. Unsupported regions are omitted.
    """

    region_results = (results,) if isinstance(results, PlanarRegionResult) else tuple(results)
    if not any(result.regions for result in region_results):
        raise RepresentativeGeometryExportError("no validated planar regions are available")
    volume_settings = volume_topology_config or VolumeTopologyConfig()
    point_tolerance = max(
        volume_settings.point_absolute_tolerance,
        _model_extent(region_results) * volume_settings.point_relative_tolerance,
    )
    arc_templates = _unique_arcs(
        tuple(
            arc
            for result in region_results
            for arc in _detected_arcs(result, curve_config)
        ),
        point_tolerance,
    )
    arc_normalizer = CircularGeometryNormalizer(
        arc_templates,
        point_tolerance=point_tolerance,
        curve_config=curve_config,
    )
    ruled_results = tuple(
        reconstruct_ruled_surfaces(
            result,
            curve_config=curve_config,
            config=ruled_surface_config,
            arc_templates=arc_templates,
        )
        for result in region_results
    )
    allowed_cap_arcs = tuple(arc for ruled in ruled_results for arc in _ruled_cap_arcs(ruled))
    groups: list[RepresentativeCurveGroup] = []
    for result_index, (result, ruled) in enumerate(zip(region_results, ruled_results)):
        label = _physical_label(result, result_index)
        preserve_unmatched_arcs = (
            volume_settings.enabled
            and result.feature_edges.source_kind == "property"
            and _result_is_three_dimensional(result)
        )
        replaced_regions = set(ruled.replaced_region_indices)
        for region in result.regions:
            if region.region_index in replaced_regions:
                continue
            for loop in (region.outer_loop, *region.hole_loops):
                simplified = simplify_planar_loop(
                    loop,
                    normal=region.normal,
                    config=curve_config,
                )
                groups.append(
                    RepresentativeCurveGroup(
                        label=label,
                        primitives=_topology_safe_primitives(
                            loop,
                            simplified.primitives,
                            allowed_arcs=allowed_cap_arcs,
                            preserve_unmatched_arcs_as_lines=preserve_unmatched_arcs,
                            tolerance=point_tolerance,
                        ),
                    )
                )
        groups.extend(
            RepresentativeCurveGroup(label=label, primitives=patch.primitives)
            for patch in ruled.patches
        )
    consolidated = arc_normalizer.consolidate_labeled(
        LabeledPrimitive(primitive, frozenset((group.label,)))
        for group in groups
        for primitive in group.primitives
    )
    return tuple(
        RepresentativeCurveGroup(
            label=(next(iter(item.labels)) if len(item.labels) == 1 else "SHARED_PROPERTIES"),
            primitives=(item.primitive,),
        )
        for item in consolidated
    )


def _write_loop(
    output: list[str],
    loop: PlanarLoop,
    *,
    normal: np.ndarray,
    curve_config: CurveSimplificationConfig | None,
    entities: _GmshEntityRegistry,
    allowed_arcs: tuple[CircularArcPrimitive, ...] = (),
    preserve_unmatched_arcs_as_lines: bool = False,
) -> tuple[int, ...]:
    simplified = simplify_planar_loop(loop, normal=normal, config=curve_config)
    primitives = _topology_safe_primitives(
        loop,
        simplified.primitives,
        allowed_arcs=allowed_arcs,
        preserve_unmatched_arcs_as_lines=preserve_unmatched_arcs_as_lines,
        tolerance=entities.point_tolerance,
    )
    return _write_primitives(
        output,
        primitives,
        original_edge_count=simplified.original_edge_count,
        entities=entities,
        comment_label="simplified_loop",
    )


def _write_primitives(
    output: list[str],
    primitives: tuple[CurvePrimitive, ...],
    *,
    original_edge_count: int,
    entities: _GmshEntityRegistry,
    comment_label: str,
) -> tuple[int, ...]:
    if not primitives:
        raise RepresentativeGeometryExportError("a representative loop has no curve primitives")
    line_count = sum(not isinstance(item, CircularArcPrimitive) for item in primitives)
    arc_count = sum(isinstance(item, CircularArcPrimitive) for item in primitives)
    max_radial_error = max(
        (
            item.max_radial_error
            for item in primitives
            if isinstance(item, CircularArcPrimitive)
        ),
        default=0.0,
    )
    output.append(
        f"// {comment_label} original_edges={original_edge_count} "
        f"lines={line_count} circles={arc_count} "
        f"max_radial_error={max_radial_error:.6g}"
    )
    return tuple(
        reference
        for primitive in primitives
        for reference in entities.add_curve(primitive)
    )


def _write_ruled_patch_surfaces(
    output: list[str],
    patch: RuledSurfacePatch,
    *,
    entities: _GmshEntityRegistry,
) -> tuple[tuple[int, int, tuple[int, ...]], ...]:
    """Write a conformal grid of four-curve surfaces for one cylindrical patch."""

    lower, _, upper_reversed, _ = tuple(
        entities.arc_normalizer.normalize_primitive(primitive)
        for primitive in patch.primitives
    )
    if not isinstance(lower, CircularArcPrimitive) or not isinstance(
        upper_reversed, CircularArcPrimitive
    ):
        raise RepresentativeGeometryExportError(
            "a ruled cylindrical patch must have circular lower and upper boundaries"
        )
    upper = _reverse_arc_primitive(upper_reversed)
    angular_parameters, axial_parameters = _ruled_patch_parameters(
        lower,
        upper,
        entities,
    )
    cell_count = (len(angular_parameters) - 1) * (len(axial_parameters) - 1)
    output.append(
        f"// ruled_loop original_edges="
        f"{sum(primitive.source_edge_count for primitive in patch.primitives)} "
        f"grid={len(angular_parameters) - 1}x{len(axial_parameters) - 1} "
        f"surfaces={cell_count}"
    )

    created: list[tuple[int, int, tuple[int, ...]]] = []
    for axial_index, (axial_start, axial_end) in enumerate(
        zip(axial_parameters, axial_parameters[1:])
    ):
        for angular_index, (angular_start, angular_end) in enumerate(
            zip(angular_parameters, angular_parameters[1:])
        ):
            primitives = _ruled_cell_primitives(
                lower,
                upper,
                angular_start,
                angular_end,
                axial_start,
                axial_end,
            )
            curve_groups = tuple(entities.add_curve(primitive) for primitive in primitives)
            if any(len(group) != 1 for group in curve_groups):
                raise RepresentativeGeometryExportError(
                    "a conformal ruled-surface cell contains an unregistered curve split"
                )
            curve_references = tuple(group[0] for group in curve_groups)
            output.append(
                f"// ruled_cell axial={axial_index} angular={angular_index}"
            )
            surface_id, orientation = entities.add_surface(
                (curve_references,),
                kind="ruled",
            )
            created.append((surface_id, orientation, curve_references))
    return tuple(created)


def _ruled_cell_primitives(
    lower: CircularArcPrimitive,
    upper: CircularArcPrimitive,
    angular_start: float,
    angular_end: float,
    axial_start: float,
    axial_end: float,
) -> tuple[CurvePrimitive, CurvePrimitive, CurvePrimitive, CurvePrimitive]:
    lower_arc = _interpolated_arc(
        lower,
        upper,
        angular_start,
        angular_end,
        axial_start,
    )
    upper_arc = _interpolated_arc(
        lower,
        upper,
        angular_start,
        angular_end,
        axial_end,
    )
    return (
        lower_arc,
        LinePrimitive(lower_arc.end.copy(), upper_arc.end.copy()),
        _reverse_arc_primitive(upper_arc),
        LinePrimitive(upper_arc.start.copy(), lower_arc.start.copy()),
    )


def _interpolated_arc(
    lower: CircularArcPrimitive,
    upper: CircularArcPrimitive,
    angular_start: float,
    angular_end: float,
    axial_parameter: float,
) -> CircularArcPrimitive:
    start = _ruled_grid_point(lower, upper, angular_start, axial_parameter)
    end = _ruled_grid_point(lower, upper, angular_end, axial_parameter)
    center = (1.0 - axial_parameter) * lower.center + axial_parameter * upper.center
    radius = float(np.linalg.norm(start - center))
    return CircularArcPrimitive(
        start=start,
        center=center,
        end=end,
        radius=radius,
        angle_degrees=(angular_end - angular_start) * lower.angle_degrees,
        max_radial_error=max(lower.max_radial_error, upper.max_radial_error),
        source_edge_count=max(
            1,
            int(round((angular_end - angular_start) * lower.source_edge_count)),
        ),
    )


def _ruled_grid_point(
    lower: CircularArcPrimitive,
    upper: CircularArcPrimitive,
    angular_parameter: float,
    axial_parameter: float,
) -> np.ndarray:
    lower_point = _arc_point(lower, angular_parameter)
    upper_point = _arc_point(upper, angular_parameter)
    return (1.0 - axial_parameter) * lower_point + axial_parameter * upper_point


def _arc_point(arc: CircularArcPrimitive, parameter: float) -> np.ndarray:
    start_vector = np.asarray(arc.start, dtype=float) - arc.center
    end_vector = np.asarray(arc.end, dtype=float) - arc.center
    radius = float(np.linalg.norm(start_vector))
    unit_start = start_vector / radius
    unit_end = end_vector / float(np.linalg.norm(end_vector))
    angle = float(np.arccos(np.clip(np.dot(unit_start, unit_end), -1.0, 1.0)))
    sine = float(np.sin(angle))
    if sine <= 0.0:
        raise RepresentativeGeometryExportError("a ruled-surface arc is degenerate")
    unit_tangent = (unit_end - np.cos(angle) * unit_start) / sine
    interpolated_angle = parameter * angle
    return arc.center + radius * (
        np.cos(interpolated_angle) * unit_start
        + np.sin(interpolated_angle) * unit_tangent
    )


def _ruled_patch_parameters(
    lower: CircularArcPrimitive,
    upper: CircularArcPrimitive,
    entities: _GmshEntityRegistry,
) -> tuple[tuple[float, ...], tuple[float, ...]]:
    """Return all angular and axial breaks required by registered shared points."""

    angular = (0.0, 1.0)
    axial = (0.0, 1.0)
    for _ in range(8):
        angular_candidates = list(angular)
        for axial_parameter in axial:
            arc = _interpolated_arc(lower, upper, 0.0, 1.0, axial_parameter)
            angular_candidates.extend(
                _registered_arc_parameters(arc, entities)
            )
        new_angular = _merge_parameters(
            angular_candidates,
            _arc_parameter_tolerance(
                lower,
                entities.arc_normalizer.tolerance_for_arc(lower),
            ),
        )

        axial_candidates = list(axial)
        for angular_parameter in new_angular:
            start = _ruled_grid_point(lower, upper, angular_parameter, 0.0)
            end = _ruled_grid_point(lower, upper, angular_parameter, 1.0)
            axial_candidates.extend(
                _registered_line_parameters(start, end, entities)
            )
        line_length = float(np.linalg.norm(upper.start - lower.start))
        axial_tolerance = (
            entities.point_tolerance / line_length if line_length > 0.0 else 1.0e-12
        )
        new_axial = _merge_parameters(axial_candidates, axial_tolerance)
        if new_angular == angular and new_axial == axial:
            break
        angular, axial = new_angular, new_axial
    return angular, axial


def _registered_arc_parameters(
    arc: CircularArcPrimitive,
    entities: _GmshEntityRegistry,
) -> tuple[float, ...]:
    start_vector = arc.start - arc.center
    end_vector = arc.end - arc.center
    radius = float(np.linalg.norm(start_vector))
    unit_start = start_vector / radius
    unit_end = end_vector / float(np.linalg.norm(end_vector))
    angle = float(np.arccos(np.clip(np.dot(unit_start, unit_end), -1.0, 1.0)))
    sine = float(np.sin(angle))
    if sine <= 0.0 or angle <= 0.0:
        return (0.0, 1.0)
    unit_tangent = (unit_end - np.cos(angle) * unit_start) / sine
    unit_normal = np.cross(unit_start, unit_tangent)
    tolerance = entities.arc_normalizer.tolerance_for_arc(arc)
    parameter_tolerance = _arc_parameter_tolerance(arc, tolerance)
    output = [0.0, 1.0]
    for coordinate in entities.point_coordinates.values():
        vector = coordinate - arc.center
        if abs(float(np.dot(vector, unit_normal))) > tolerance:
            continue
        planar_radius = float(
            np.hypot(np.dot(vector, unit_start), np.dot(vector, unit_tangent))
        )
        if abs(planar_radius - radius) > tolerance:
            continue
        point_angle = float(
            np.arctan2(np.dot(vector, unit_tangent), np.dot(vector, unit_start))
        )
        parameter = point_angle / angle
        if -parameter_tolerance <= parameter <= 1.0 + parameter_tolerance:
            output.append(min(1.0, max(0.0, parameter)))
    return tuple(output)


def _registered_line_parameters(
    start: np.ndarray,
    end: np.ndarray,
    entities: _GmshEntityRegistry,
) -> tuple[float, ...]:
    vector = end - start
    length_squared = float(np.dot(vector, vector))
    length = float(np.sqrt(length_squared))
    if length <= 0.0:
        return (0.0, 1.0)
    tolerance = entities.point_tolerance
    parameter_tolerance = tolerance / length
    output = [0.0, 1.0]
    for coordinate in entities.point_coordinates.values():
        parameter = float(np.dot(coordinate - start, vector) / length_squared)
        if not -parameter_tolerance <= parameter <= 1.0 + parameter_tolerance:
            continue
        closest = start + parameter * vector
        if np.linalg.norm(coordinate - closest) <= tolerance:
            output.append(min(1.0, max(0.0, parameter)))
    return tuple(output)


def _arc_parameter_tolerance(
    arc: CircularArcPrimitive,
    point_tolerance: float,
) -> float:
    angle = max(float(np.radians(arc.angle_degrees)), 1.0e-12)
    return max(1.0e-12, point_tolerance / max(arc.radius * angle, 1.0e-30))


def _merge_parameters(
    values: Iterable[float],
    tolerance: float,
) -> tuple[float, ...]:
    merged: list[float] = []
    for value in sorted(min(1.0, max(0.0, float(item))) for item in values):
        if not merged or value - merged[-1] > tolerance:
            merged.append(value)
    merged[0] = 0.0
    merged[-1] = 1.0
    return tuple(merged)


@dataclass
class _GmshEntityRegistry:
    """Write and reuse geometrically coincident Gmsh entities."""

    output: list[str]
    point_tolerance: float
    arc_normalizer: CircularGeometryNormalizer
    next_point_id: int = 1
    next_curve_id: int = 1
    next_curve_loop_id: int = 1
    next_surface_id: int = 1
    point_coordinates: dict[int, np.ndarray] = field(default_factory=dict)
    point_bins: dict[tuple[int, int, int], list[int]] = field(
        default_factory=lambda: defaultdict(list)
    )
    circular_point_bins: dict[tuple[int, int, int], list[int]] = field(
        default_factory=lambda: defaultdict(list)
    )
    line_entities: dict[tuple[int, int], int] = field(default_factory=dict)
    circle_entities: dict[tuple[int, int, int], int] = field(default_factory=dict)
    circle_angles_degrees: dict[int, float] = field(default_factory=dict)
    surface_entities: dict[
        tuple[str, tuple[tuple[int, ...], ...]], tuple[int, dict[int, int]]
    ] = field(default_factory=dict)

    def add_point(self, point: np.ndarray) -> int:
        coordinate = self.arc_normalizer.snap_point(point)
        existing = self._find_point(coordinate)
        if existing is not None:
            return existing

        identifier = self.next_point_id
        self.next_point_id += 1
        self.point_coordinates[identifier] = coordinate.copy()
        self.point_bins[self._point_bin(coordinate)].append(identifier)
        self.circular_point_bins[self._circular_point_bin(coordinate)].append(identifier)
        self.output.append(
            f"Point({identifier}) = "
            f"{{{_number(coordinate[0])}, {_number(coordinate[1])}, {_number(coordinate[2])}, "
            "representative_mesh_size};"
        )
        return identifier

    def add_curve(self, primitive: CurvePrimitive) -> tuple[int, ...]:
        primitive = self.arc_normalizer.normalize_primitive(primitive)
        start_id = self.add_point(primitive.start)
        end_id = self.add_point(primitive.end)
        if start_id == end_id:
            raise RepresentativeGeometryExportError("a representative curve has coincident endpoints")

        if isinstance(primitive, CircularArcPrimitive):
            center_id = self.add_point(primitive.center)
            ordered_points = self._points_on_arc(primitive, start_id, end_id, center_id)
            return tuple(
                self._add_circle_segment(first, center_id, second)
                for first, second in zip(ordered_points, ordered_points[1:])
            )

        ordered_points = self._points_on_line(primitive.start, primitive.end, start_id, end_id)
        return tuple(
            self._add_line_segment(first, second)
            for first, second in zip(ordered_points, ordered_points[1:])
        )

    def _add_line_segment(self, start_id: int, end_id: int) -> int:
        low, high = sorted((start_id, end_id))
        key = (low, high)
        existing = self.line_entities.get(key)
        orientation = 1 if start_id == low else -1
        if existing is not None:
            return orientation * existing
        identifier = self.next_curve_id
        self.next_curve_id += 1
        self.line_entities[key] = identifier
        self.output.append(f"Line({identifier}) = {{{low}, {high}}};")
        return orientation * identifier

    def _add_circle_segment(self, start_id: int, center_id: int, end_id: int) -> int:
        low, high = sorted((start_id, end_id))
        key = (low, center_id, high)
        existing = self.circle_entities.get(key)
        orientation = 1 if start_id == low else -1
        if existing is not None:
            return orientation * existing
        identifier = self.next_curve_id
        self.next_curve_id += 1
        self.circle_entities[key] = identifier
        first, last = (start_id, end_id) if orientation > 0 else (end_id, start_id)
        first_vector = self.point_coordinates[first] - self.point_coordinates[center_id]
        last_vector = self.point_coordinates[last] - self.point_coordinates[center_id]
        denominator = float(np.linalg.norm(first_vector) * np.linalg.norm(last_vector))
        self.circle_angles_degrees[identifier] = float(
            np.degrees(
                np.arccos(
                    np.clip(np.dot(first_vector, last_vector) / denominator, -1.0, 1.0)
                )
            )
        )
        self.output.append(f"Circle({identifier}) = {{{first}, {center_id}, {last}}};")
        return orientation * identifier

    def _points_on_line(
        self,
        start: np.ndarray,
        end: np.ndarray,
        start_id: int,
        end_id: int,
    ) -> tuple[int, ...]:
        vector = np.asarray(end, dtype=float) - np.asarray(start, dtype=float)
        length_squared = float(np.dot(vector, vector))
        length = float(np.sqrt(length_squared))
        parameter_tolerance = self.point_tolerance / length if length > 0.0 else 0.0
        candidates = [(0.0, start_id), (1.0, end_id)]
        for identifier, coordinate in self.point_coordinates.items():
            if identifier in {start_id, end_id}:
                continue
            parameter = float(np.dot(coordinate - start, vector) / length_squared)
            if parameter <= parameter_tolerance or parameter >= 1.0 - parameter_tolerance:
                continue
            closest = np.asarray(start, dtype=float) + parameter * vector
            if np.linalg.norm(coordinate - closest) <= self.point_tolerance:
                candidates.append((parameter, identifier))
        return tuple(identifier for _, identifier in sorted(candidates))

    def _points_on_arc(
        self,
        primitive: CircularArcPrimitive,
        start_id: int,
        end_id: int,
        center_id: int,
    ) -> tuple[int, ...]:
        start_vector = np.asarray(primitive.start, dtype=float) - primitive.center
        end_vector = np.asarray(primitive.end, dtype=float) - primitive.center
        axis = np.cross(start_vector, end_vector)
        axis_length = float(np.linalg.norm(axis))
        if axis_length <= 0.0:
            return (start_id, end_id)
        axis /= axis_length
        radius = float(primitive.radius)
        angle_end = float(
            np.arctan2(
                np.dot(axis, np.cross(start_vector, end_vector)),
                np.dot(start_vector, end_vector),
            )
        )
        arc_tolerance = self.arc_normalizer.tolerance_for_arc(primitive)
        angle_tolerance = arc_tolerance / radius if radius > 0.0 else 0.0
        candidates = [(0.0, start_id), (angle_end, end_id)]
        for identifier, coordinate in self.point_coordinates.items():
            if identifier in {start_id, end_id, center_id}:
                continue
            vector = coordinate - primitive.center
            if abs(float(np.linalg.norm(vector)) - radius) > arc_tolerance:
                continue
            if abs(float(np.dot(vector, axis))) > arc_tolerance:
                continue
            angle = float(
                np.arctan2(
                    np.dot(axis, np.cross(start_vector, vector)),
                    np.dot(start_vector, vector),
                )
            )
            if angle <= angle_tolerance or angle >= angle_end - angle_tolerance:
                continue
            candidates.append((angle, identifier))
        return tuple(identifier for _, identifier in sorted(candidates))

    def add_surface(
        self,
        loops: tuple[tuple[int, ...], ...],
        *,
        kind: str,
    ) -> tuple[int, int]:
        if kind not in {"plane", "ruled"}:
            raise ValueError(f"unsupported representative surface kind: {kind!r}")
        if not loops or any(not loop for loop in loops):
            raise RepresentativeGeometryExportError("a representative surface has an empty loop")
        flattened = tuple(reference for loop in loops for reference in loop)
        if len({abs(reference) for reference in flattened}) != len(flattened):
            raise RepresentativeGeometryExportError("a representative surface repeats a curve")
        key = (
            kind,
            tuple(sorted(tuple(sorted(abs(reference) for reference in loop)) for loop in loops)),
        )
        requested_signs = {
            abs(reference): 1 if reference > 0 else -1 for reference in flattened
        }
        existing = self.surface_entities.get(key)
        if existing is not None:
            identifier, stored_signs = existing
            orientation_products = {
                requested_signs[curve_id] * stored_signs[curve_id]
                for curve_id in requested_signs
            }
            if len(orientation_products) != 1:
                raise RepresentativeGeometryExportError(
                    "coincident surface loops have inconsistent curve orientations"
                )
            return identifier, orientation_products.pop()

        loop_ids: list[int] = []
        for loop in loops:
            loop_id = self.next_curve_loop_id
            self.next_curve_loop_id += 1
            references = ", ".join(str(reference) for reference in loop)
            self.output.append(f"Curve Loop({loop_id}) = {{{references}}};")
            loop_ids.append(loop_id)
        identifier = self.next_surface_id
        self.next_surface_id += 1
        loop_references = ", ".join(str(loop_id) for loop_id in loop_ids)
        entity_name = "Plane Surface" if kind == "plane" else "Surface"
        self.output.append(f"{entity_name}({identifier}) = {{{loop_references}}};")
        self.surface_entities[key] = (identifier, requested_signs)
        return identifier, 1

    def _find_point(self, coordinate: np.ndarray) -> int | None:
        key = self._point_bin(coordinate)
        offsets = product((-1, 0, 1), repeat=3) if self.point_tolerance > 0.0 else ((0, 0, 0),)
        for offset in offsets:
            neighbor = tuple(key[index] + offset[index] for index in range(3))
            for identifier in self.point_bins.get(neighbor, ()):
                if np.linalg.norm(self.point_coordinates[identifier] - coordinate) <= self.point_tolerance:
                    return identifier
        circular_key = self._circular_point_bin(coordinate)
        circular_offsets = (
            product((-1, 0, 1), repeat=3)
            if self.arc_normalizer.circular_point_tolerance > 0.0
            else ((0, 0, 0),)
        )
        for offset in circular_offsets:
            neighbor = tuple(circular_key[index] + offset[index] for index in range(3))
            for identifier in self.circular_point_bins.get(neighbor, ()):
                existing = self.point_coordinates[identifier]
                if self.arc_normalizer.circular_points_coincident(existing, coordinate):
                    return identifier
        return None

    def _point_bin(self, coordinate: np.ndarray) -> tuple[int, int, int]:
        if self.point_tolerance == 0.0:
            return tuple(hash(float(value)) for value in coordinate)
        return tuple(int(np.floor(float(value) / self.point_tolerance)) for value in coordinate)

    def _circular_point_bin(self, coordinate: np.ndarray) -> tuple[int, int, int]:
        tolerance = self.arc_normalizer.circular_point_tolerance
        if tolerance == 0.0:
            return tuple(hash(float(value)) for value in coordinate)
        return tuple(int(np.floor(float(value) / tolerance)) for value in coordinate)


def _append_topology_record(
    records: list[SurfaceTopologyRecord],
    result: PlanarRegionResult,
    *,
    surface_id: int,
    orientation: int,
    curve_references: tuple[int, ...],
) -> None:
    feature_edges = result.feature_edges
    if feature_edges.source_kind != "property" or feature_edges.property_id is None:
        return
    records.append(
        SurfaceTopologyRecord(
            property_id=int(feature_edges.property_id),
            surface_id=surface_id,
            orientation_to_source=orientation,
            curve_references=curve_references,
            property_label=_physical_label(result, 0),
        )
    )


def _globally_conformal_ruled_results(
    results: tuple[PlanarRegionResult, ...],
    ruled_results: tuple[RuledSurfaceResult, ...],
    *,
    curve_config: CurveSimplificationConfig | None,
    tolerance: float,
) -> tuple[RuledSurfaceResult, ...]:
    """Keep curved patches only when coincident Property arcs agree globally."""

    active_patches = [list(ruled.patches) for ruled in ruled_results]
    while True:
        unmatched: list[CircularArcPrimitive] = []
        for result, patches in zip(results, active_patches):
            matched = tuple(
                primitive
                for patch in patches
                for primitive in (patch.primitives[0], patch.primitives[2])
                if isinstance(primitive, CircularArcPrimitive)
            )
            unmatched.extend(
                _unmatched_detected_arcs(
                    result,
                    matched,
                    curve_config=curve_config,
                    tolerance=tolerance,
                )
            )

        changed = False
        for index, patches in enumerate(active_patches):
            kept = [
                patch
                for patch in patches
                if not any(
                    _same_arc_geometry(cap_arc, unmatched_arc, tolerance)
                    for cap_arc in (patch.primitives[0], patch.primitives[2])
                    if isinstance(cap_arc, CircularArcPrimitive)
                    for unmatched_arc in unmatched
                )
            ]
            if len(kept) != len(patches):
                active_patches[index] = kept
                changed = True
        if not changed:
            break

    output: list[RuledSurfaceResult] = []
    for original, patches in zip(ruled_results, active_patches):
        replaced = tuple(
            sorted(region for patch in patches for region in patch.source_region_indices)
        )
        removed_count = len(original.patches) - len(patches)
        diagnostics = original.diagnostics
        if removed_count:
            diagnostics = (
                *diagnostics,
                f"nonconformal_ruled_patches_removed={removed_count}",
            )
        output.append(RuledSurfaceResult(tuple(patches), replaced, diagnostics))
    return tuple(output)


def _detected_arcs(
    result: PlanarRegionResult,
    curve_config: CurveSimplificationConfig | None,
) -> tuple[CircularArcPrimitive, ...]:
    return tuple(
        primitive
        for region in result.regions
        for loop in (region.outer_loop, *region.hole_loops)
        for primitive in simplify_planar_loop(
            loop,
            normal=region.normal,
            config=curve_config,
        ).primitives
        if isinstance(primitive, CircularArcPrimitive)
    )


def _unmatched_detected_arcs(
    result: PlanarRegionResult,
    matched: tuple[CircularArcPrimitive, ...],
    *,
    curve_config: CurveSimplificationConfig | None,
    tolerance: float,
) -> tuple[CircularArcPrimitive, ...]:
    unmatched: list[CircularArcPrimitive] = []
    for region in result.regions:
        for loop in (region.outer_loop, *region.hole_loops):
            simplified = simplify_planar_loop(
                loop,
                normal=region.normal,
                config=curve_config,
            )
            arcs = tuple(
                primitive
                for primitive in simplified.primitives
                if isinstance(primitive, CircularArcPrimitive)
            )
            missing = tuple(
                arc
                for arc in arcs
                if not any(_same_arc_geometry(arc, item, tolerance) for item in matched)
            )
            if missing and arcs and len(arcs) == len(simplified.primitives):
                unmatched.extend(arcs)
            else:
                unmatched.extend(missing)
    return tuple(unmatched)


def _unique_arcs(
    arcs: tuple[CircularArcPrimitive, ...],
    tolerance: float,
) -> tuple[CircularArcPrimitive, ...]:
    unique: list[CircularArcPrimitive] = []
    for arc in arcs:
        if not any(_same_arc_geometry(arc, existing, tolerance) for existing in unique):
            unique.append(arc)
    return tuple(unique)


def _pre_register_representative_points(
    entities: _GmshEntityRegistry,
    results: tuple[PlanarRegionResult, ...],
    ruled_results: tuple[RuledSurfaceResult, ...],
    *,
    allowed_cap_arcs: tuple[CircularArcPrimitive, ...],
    curve_config: CurveSimplificationConfig | None,
    volume_topology_config: VolumeTopologyConfig,
) -> None:
    """Register all simplified endpoints before conformal curve subdivision."""

    for result, ruled in zip(results, ruled_results):
        preserve_unmatched_arcs = (
            volume_topology_config.enabled
            and result.feature_edges.source_kind == "property"
            and _result_is_three_dimensional(result)
        )
        replaced_regions = set(ruled.replaced_region_indices)
        primitive_groups: list[tuple[CurvePrimitive, ...]] = []
        for region in result.regions:
            if region.region_index in replaced_regions:
                continue
            for loop in (region.outer_loop, *region.hole_loops):
                simplified = simplify_planar_loop(loop, normal=region.normal, config=curve_config)
                primitive_groups.append(
                    _topology_safe_primitives(
                        loop,
                        simplified.primitives,
                        allowed_arcs=allowed_cap_arcs,
                        preserve_unmatched_arcs_as_lines=preserve_unmatched_arcs,
                        tolerance=entities.point_tolerance,
                    )
                )
        primitive_groups.extend(
            tuple(entities.arc_normalizer.normalize_primitive(primitive) for primitive in patch.primitives)
            for patch in ruled.patches
        )
        for primitives in primitive_groups:
            for primitive in primitives:
                entities.add_point(primitive.start)
                entities.add_point(primitive.end)
                if isinstance(primitive, CircularArcPrimitive):
                    entities.add_point(primitive.center)

    patches = tuple(patch for ruled in ruled_results for patch in ruled.patches)
    for _ in range(8):
        point_count = len(entities.point_coordinates)
        for patch in patches:
            lower, _, upper_reversed, _ = tuple(
                entities.arc_normalizer.normalize_primitive(primitive)
                for primitive in patch.primitives
            )
            if not isinstance(lower, CircularArcPrimitive) or not isinstance(
                upper_reversed, CircularArcPrimitive
            ):
                continue
            upper = _reverse_arc_primitive(upper_reversed)
            angular_parameters, axial_parameters = _ruled_patch_parameters(
                lower,
                upper,
                entities,
            )
            for axial_parameter in axial_parameters:
                entities.add_point(
                    (1.0 - axial_parameter) * lower.center
                    + axial_parameter * upper.center
                )
                for angular_parameter in angular_parameters:
                    entities.add_point(
                        _ruled_grid_point(
                            lower,
                            upper,
                            angular_parameter,
                            axial_parameter,
                        )
                    )
        if len(entities.point_coordinates) == point_count:
            break


def _ruled_cap_arcs(ruled: RuledSurfaceResult) -> tuple[CircularArcPrimitive, ...]:
    return tuple(
        primitive
        for patch in ruled.patches
        for primitive in (patch.primitives[0], patch.primitives[2])
        if isinstance(primitive, CircularArcPrimitive)
    )


def _topology_safe_primitives(
    loop: PlanarLoop,
    primitives: tuple[CurvePrimitive, ...],
    *,
    allowed_arcs: tuple[CircularArcPrimitive, ...],
    preserve_unmatched_arcs_as_lines: bool,
    tolerance: float,
) -> tuple[CurvePrimitive, ...]:
    if not preserve_unmatched_arcs_as_lines:
        return primitives

    force_full_circle_fallback = False
    if primitives and all(isinstance(item, CircularArcPrimitive) for item in primitives):
        if any(
            not any(_same_arc_geometry(item, allowed, tolerance) for allowed in allowed_arcs)
            for item in primitives
        ):
            force_full_circle_fallback = True

    output: list[CurvePrimitive] = []
    for primitive in primitives:
        if not isinstance(primitive, CircularArcPrimitive):
            output.append(primitive)
            continue
        is_allowed = not force_full_circle_fallback and any(
            _same_arc_geometry(primitive, allowed, tolerance) for allowed in allowed_arcs
        )
        if is_allowed:
            output.append(_snap_arc_to_loop_points(loop, primitive, tolerance))
        else:
            output.extend(_arc_source_chords(loop, primitive, tolerance))
    return _promote_line_runs_to_arcs(tuple(output), allowed_arcs, tolerance)


def _same_arc_geometry(
    first: CircularArcPrimitive,
    second: CircularArcPrimitive,
    tolerance: float,
) -> bool:
    match_tolerance = max(
        tolerance,
        2.0 * first.max_radial_error,
        2.0 * second.max_radial_error,
        min(first.radius, second.radius) * 1.0e-4,
    )
    if abs(first.radius - second.radius) > match_tolerance:
        return False
    if np.linalg.norm(first.center - second.center) > match_tolerance:
        return False
    direct = max(
        float(np.linalg.norm(first.start - second.start)),
        float(np.linalg.norm(first.end - second.end)),
    )
    reverse = max(
        float(np.linalg.norm(first.start - second.end)),
        float(np.linalg.norm(first.end - second.start)),
    )
    return min(direct, reverse) <= match_tolerance


def _snap_arc_to_loop_points(
    loop: PlanarLoop,
    arc: CircularArcPrimitive,
    tolerance: float,
) -> CircularArcPrimitive:
    chords = _arc_source_chords(loop, arc, tolerance)
    snapped = _arc_with_exact_endpoints(arc, chords[0].start, chords[-1].end)
    return arc if snapped is None else snapped


def _promote_line_runs_to_arcs(
    primitives: tuple[CurvePrimitive, ...],
    allowed_arcs: tuple[CircularArcPrimitive, ...],
    tolerance: float,
) -> tuple[CurvePrimitive, ...]:
    if not primitives or not allowed_arcs:
        return primitives
    count = len(primitives)
    candidates: list[tuple[int, int, CircularArcPrimitive, float]] = []
    for start_index in range(count):
        for template in allowed_arcs:
            edge_count = template.source_edge_count
            indices = tuple((start_index + offset) % count for offset in range(edge_count))
            if edge_count >= count or not all(
                isinstance(primitives[index], LinePrimitive) for index in indices
            ):
                continue
            lines = tuple(primitives[index] for index in indices)
            assert all(isinstance(line, LinePrimitive) for line in lines)
            promoted = _line_run_arc(lines, template, tolerance)
            if promoted is not None:
                arc, error = promoted
                candidates.append((start_index, edge_count, arc, error))

    selected: dict[int, tuple[int, CircularArcPrimitive]] = {}
    occupied: set[int] = set()
    for start_index, edge_count, arc, error in sorted(
        candidates,
        key=lambda item: (-item[1], item[3], item[0]),
    ):
        indices = {(start_index + offset) % count for offset in range(edge_count)}
        if occupied.isdisjoint(indices):
            selected[start_index] = (edge_count, arc)
            occupied.update(indices)
    if not selected:
        return primitives

    uncovered = sorted(set(range(count)) - occupied)
    current = uncovered[0] if uncovered else min(selected)
    output: list[CurvePrimitive] = []
    processed = 0
    while processed < count:
        replacement = selected.get(current)
        if replacement is None:
            output.append(primitives[current])
            current = (current + 1) % count
            processed += 1
        else:
            edge_count, arc = replacement
            output.append(arc)
            current = (current + edge_count) % count
            processed += edge_count
    return tuple(output)


def _line_run_arc(
    lines: tuple[LinePrimitive, ...],
    template: CircularArcPrimitive,
    tolerance: float,
) -> tuple[CircularArcPrimitive, float] | None:
    start = lines[0].start
    end = lines[-1].end
    match_tolerance = max(
        tolerance,
        3.0 * template.max_radial_error,
        template.radius * 1.0e-4,
    )
    direct = max(
        float(np.linalg.norm(start - template.start)),
        float(np.linalg.norm(end - template.end)),
    )
    reverse = max(
        float(np.linalg.norm(start - template.end)),
        float(np.linalg.norm(end - template.start)),
    )
    if min(direct, reverse) > match_tolerance:
        return None
    oriented = template if direct <= reverse else _reverse_arc_primitive(template)
    arc = _arc_with_exact_endpoints(oriented, start, end)
    if arc is None:
        return None
    samples = np.vstack((start, *(line.end for line in lines)))
    radial_error = float(
        np.max(np.abs(np.linalg.norm(samples - arc.center, axis=1) - arc.radius))
    )
    if radial_error > match_tolerance:
        return None
    return arc, radial_error


def _arc_with_exact_endpoints(
    template: CircularArcPrimitive,
    start: np.ndarray,
    end: np.ndarray,
) -> CircularArcPrimitive | None:
    first_template = template.start - template.center
    second_template = template.end - template.center
    normal = np.cross(first_template, second_template)
    normal_length = float(np.linalg.norm(normal))
    chord = end - start
    perpendicular = np.cross(normal, chord)
    perpendicular_length = float(np.linalg.norm(perpendicular))
    if normal_length <= 0.0 or perpendicular_length <= 0.0:
        return None
    perpendicular /= perpendicular_length
    midpoint = 0.5 * (start + end)
    center = midpoint + float(np.dot(template.center - midpoint, perpendicular)) * perpendicular
    first = start - center
    second = end - center
    radius = float(np.linalg.norm(first))
    if radius <= 0.0:
        return None
    angle = float(
        np.degrees(
            np.arccos(
                np.clip(np.dot(first, second) / (radius * radius), -1.0, 1.0)
            )
        )
    )
    if not 0.0 < angle < 180.0:
        return None
    return CircularArcPrimitive(
        start=start.copy(),
        center=center,
        end=end.copy(),
        radius=radius,
        angle_degrees=angle,
        max_radial_error=template.max_radial_error,
        source_edge_count=template.source_edge_count,
    )


def _reverse_arc_primitive(arc: CircularArcPrimitive) -> CircularArcPrimitive:
    return CircularArcPrimitive(
        start=arc.end.copy(),
        center=arc.center.copy(),
        end=arc.start.copy(),
        radius=arc.radius,
        angle_degrees=arc.angle_degrees,
        max_radial_error=arc.max_radial_error,
        source_edge_count=arc.source_edge_count,
        plane_normal=(None if arc.plane_normal is None else -arc.plane_normal.copy()),
    )


def _arc_source_chords(
    loop: PlanarLoop,
    arc: CircularArcPrimitive,
    tolerance: float,
) -> tuple[LinePrimitive, ...]:
    points = np.asarray(loop.points, dtype=float)
    recovery_tolerance = max(
        tolerance,
        2.0 * arc.max_radial_error,
        arc.radius * 1.0e-8,
    )
    distances = np.linalg.norm(points - arc.start, axis=1)
    start_index = int(np.argmin(distances))
    if distances[start_index] > recovery_tolerance:
        raise RepresentativeGeometryExportError(
            "could not recover source chords for an unmatched circular arc"
        )
    end_index = (start_index + arc.source_edge_count) % len(points)
    if np.linalg.norm(points[end_index] - arc.end) > recovery_tolerance:
        raise RepresentativeGeometryExportError(
            "unmatched circular arc source-edge ordering is inconsistent"
        )
    return tuple(
        LinePrimitive(
            start=points[(start_index + offset) % len(points)].copy(),
            end=points[(start_index + offset + 1) % len(points)].copy(),
        )
        for offset in range(arc.source_edge_count)
    )


def _result_is_three_dimensional(result: PlanarRegionResult) -> bool:
    point_groups = [
        loop.points
        for region in result.regions
        for loop in (region.outer_loop, *region.hole_loops)
    ]
    if not point_groups:
        return False
    points = np.vstack(point_groups)
    extent = float(np.linalg.norm(np.ptp(points, axis=0)))
    tolerance = max(1.0e-12, extent * 1.0e-10)
    return int(np.linalg.matrix_rank(points - points[0], tol=tolerance)) >= 3


def _model_extent(results: tuple[PlanarRegionResult, ...]) -> float:
    point_groups = [
        loop.points
        for result in results
        for region in result.regions
        for loop in (region.outer_loop, *region.hole_loops)
    ]
    if not point_groups:
        return 0.0
    points = np.vstack(point_groups)
    return float(np.linalg.norm(np.ptp(points, axis=0)))


def _physical_label(result: PlanarRegionResult, result_index: int) -> str:
    feature_edges = result.feature_edges
    if feature_edges.source_kind == "property" and feature_edges.property_id is not None:
        property_ids = tuple(getattr(feature_edges, "property_ids", ()))
        if len(property_ids) > 1:
            suffix = "_".join(f"P{property_id}" for property_id in property_ids)
            return f"PROPERTY_GROUP_{suffix}"
        return f"PROPERTY_P{feature_edges.property_id}"
    if feature_edges.source_kind == "exterior":
        return "EXTERIOR"
    if feature_edges.source_kind == "interface" and feature_edges.property_pair is not None:
        property_a, property_b = feature_edges.property_pair
        patch = "" if feature_edges.patch_index is None else f"_PATCH{feature_edges.patch_index}"
        return f"INTERFACE_P{property_a}_P{property_b}{patch}"
    return f"REPRESENTATIVE_{result_index}"


def _number(value: float) -> str:
    return format(float(value), ".17g")
